language: python
python:
- '3.6'
cache: pip
node_js:
  - "10.16.3"
os: linux
dist: bionic
env:
  global:
    - NODE_OPTIONS="--max_old_space_size=4096"

install:
  - pip install codecov pytest-cov
  - pip install -e .
  - pip install -e .[dev]
  - export ETH_PRIVATE_KEY=$TEST_ETH_PRIVATE_KEY

before_script:
  - "flake8 ."

jobs:
  include:
    - stage: test
      script:
        - git clone https://${CI_USER_TOKEN}@github.com/skalenetwork/skale-manager.git
        - cd skale-manager/
        # - git checkout enhancement/SKALE-1684-Move-to-byzantium
        - npm i
        - cat truffle-config.js
        - sed -i 's/petersburg/byzantium/g' truffle-config.js
        - cat truffle-config.js
        - PRIVATE_KEY=$SKALE_PY_TESTNET_PRIVATE_KEY NETWORK=SKALE_private_testnet bash scripts/deploy.sh
        - cp data/SKALE_private_testnet.json ../test_abi.json && cd ..
        - ./scripts/run-tests.sh
      after_script:
        - codecov -t $CODECOV_TOKEN
    - stage: deploy
      if: branch IN (develop, beta, stable, master)
      script:
        - export VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./scripts/calculate_version.sh)
        - echo "Version $VERSION"
        - bash ./scripts/build.sh
      before_deploy:
        # Set up git user name and tag this commit
        - (
          test ! $TRAVIS_TAG &&
          git config --local user.name "skale-travis" &&
          git config --local user.email "$GITHUB_EMAIL" &&
          export TRAVIS_TAG=$VERSION &&
          git tag "$TRAVIS_TAG" &&
          git push https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_TAG
          ) || true
      deploy:
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          name: $VERSION @ $(date +'%d.%m.%Y %R')
          on:
            repo: $TRAVIS_REPO_SLUG
            branch: master
        - provider: releases
          api_key: "$GITHUB_OAUTH_TOKEN"
          skip_cleanup: true
          prerelease: true
          name: $VERSION @ $(date +'%d.%m.%Y %R')
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - master
              - develop
              - beta
        - provider: script
          skip_cleanup: true
          script: bash $TRAVIS_BUILD_DIR/scripts/publish.sh
          on:
            repo: $TRAVIS_REPO_SLUG
            branch:
              - master
              - stable
              - develop
              - beta
